version: "3.7"

services:
  # for local development
  frontend:
    build:
      context: ./expense-tracker-frontend
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - './expense-tracker-frontend:/app'
    command: ["yarn", "serve"]

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./expense-tracker-rest/seeder:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"